name: Publish Python Package to PyPI

on:
  release:
    types: [published]

jobs:
  build-and-publish:
    if: github.event.release.prerelease == false
    name: Build and publish Python distributions to PyPI
    runs-on: ubuntu-latest
    environment: pypi
    permissions:
      id-token: write  # This is required for trusted publishing

    steps:
      - name: Checkout repo + submodules
        uses: actions/checkout@v5
        with:
          submodules: recursive
          fetch-depth: 0  # fetch full history and tags for versioning

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"

      - name: Set up uv
        uses: astral-sh/setup-uv@v1

      - name: Sync dependencies
        run: uv sync --group dev --frozen

      - name: Build package
        run: uv run python -m build

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
